// Test: Display am Grove-Anschluss A1 verbinden und Beispielbild zeichnen
eInk.init(SerialPin.C17, SerialPin.C16)
eInk.clear(EInkColor.White)
eInk.drawRect(0, 0, 152, 152, EInkColor.Black, false)
eInk.drawRect(0, 0, 152, 28, EInkColor.Red, true)
eInk.showText("Calliope", (152 - eInk.textWidth("Calliope", 2)) / 2, 7, 2, EInkColor.White)
eInk.showText("Grüße aus der\nSchule! 23°C", 8, 40, 1, EInkColor.Black)
eInk.drawCircle(40, 105, 25, EInkColor.Black, false)
eInk.drawCircle(40, 105, 12, EInkColor.Red, true)
eInk.drawLine(80, 80, 144, 144, EInkColor.Red)
eInk.drawImage(images.iconImage(IconNames.Heart), 95, 70, 8, EInkColor.Black)
eInk.showNumber(42, 110, 125, 2, EInkColor.Black)
eInk.update()
basic.showIcon(eInk.lastUpdateSuccessful() ? IconNames.Yes : IconNames.No)
