// Test: Display am Grove-Anschluss A1 verbinden und Beispielbild zeichnen
eInk.init(SerialPin.C17, SerialPin.C16)
eInk.clear(EInkColor.White)
eInk.drawRect(0, 0, 152, 152, EInkColor.Black, false)
eInk.drawRect(0, 0, 152, 28, EInkColor.Red, true)
eInk.showText("Calliope", (152 - eInk.textWidth("Calliope", 2)) / 2, 7, 2, EInkColor.White)
eInk.showText("Grüße aus der\nSchule! 23°C", 8, 40, 1, EInkColor.Black)
eInk.drawCircle(40, 105, 25, EInkColor.Black, false)
eInk.drawCircle(40, 105, 12, EInkColor.Red, true)
eInk.drawLine(80, 80, 144, 144, EInkColor.Red)
eInk.drawImage(images.iconImage(IconNames.Heart), 95, 70, 8, EInkColor.Black)
eInk.showNumber(42, 110, 125, 2, EInkColor.Black)
// Grafik aus dem Bild-Konverter (10 x 3 Pixel: schwarz, rot, weiß/transparent)
eInk.drawBitmap("AQoD/8AAAFVAAAD/wFVA", 8, 140, 2)
eInk.update()
basic.showIcon(eInk.lastUpdateSuccessful() ? IconNames.Yes : IconNames.No)

// Schriften testen (nach 180 s, damit das Display nicht zu oft aktualisiert)
basic.pause(180000)
eInk.clear(EInkColor.White)
eInk.setFont(EInkFont.Roboto32)
eInk.showText("Grüße!", (152 - eInk.textWidth("Grüße!", 1)) / 2, 2, 1, EInkColor.Red)
eInk.setFont(EInkFont.Roboto16)
let y = 2 + 40
eInk.showText("Roboto 16: ein längerer Text mit Umbruch", 4, y, 1, EInkColor.Black)
eInk.setFont(EInkFont.RobotoMono12)
eInk.showText("Mono 12: 23.5 °C", 4, 110, 1, EInkColor.Black)
eInk.setFont(EInkFont.Standard)
eInk.showText("Standard 5x7", 4, 110 + eInk.textHeight(1) + 20, 1, EInkColor.Black)
eInk.update()
